[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"
rustflags = [
  "-C", "link-arg=-Wl,-rpath,/usr/lib/x86_64-linux-gnu",
  "-C", "link-arg=-L/usr/lib/x86_64-linux-gnu"
]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
