name: Cross-Compile Gem

on:
  push:
    branches: [master]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Cross-compile gems for ${{ matrix.ruby }} on ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4', head, jruby, jruby-head, truffleruby, truffleruby-head]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Install cURL Headers
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Run tests
        run: bundle exec rake rust_test
     
      - name: Cross-compile gems
        run: bundle exec rake gem:all-platforms
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cross-compiled-gems
          path: pkg/*.gem
          retention-days: 7